package com.codeevo.agent.model.payload;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;
import java.util.Map;

/**
 * Payload for GRAPH_UPDATE events.
 * Contains ReactFlow node/edge data generated by the Visual Architect Agent.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class GraphUpdatePayload {
    private List<Map<String, Object>> nodes;
    private List<Map<String, Object>> edges;
    private String summary;
    /** Message displayed alongside Approve/Reject buttons */
    private String permissionMessage;
    /** Token the client sends back in UserFeedback to trigger code generation */
    private String approvalToken;
}
